language: node_js
node_js:
- 10.16.0
dist: xenial
sudo: required
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
script:
- ng lint
- ng build --prod
deploy:
  provider: s3
  access_key_id: AKIAUR2E2PCTQ5ZBVWFR
  secret_access_key:
    secure: OCgfD8TD0m5FBCAfNpgc9H8ZUDkHMFAeLYkdawEpsfYZCVpiB2MdRQz77VTjpd2JJuHxe4lObKA8anc8mW05ByeGoyW5xWW9erPb9gGhCAD9hMGei6S4X1c3HWNQIoxRE6sCAK/jGVChSsdj4lnekZv1hzUj7VP0VyGZza+1tgr3DdSxuwMhLDCJcx+juyn5U0/ffv+LIrw6wj4+8dKH/s8cjHw74TRqmigPztXZTz3MRAIO8Uf8wu1Dvj00iSf2Q2s06jY8UTQNUy4cxUgIWfjZdOE6EvDLvaC0LAkDGPia2F9WJVRf2dyRsAlL5lNT6QCZN/Ozj2iipqs3NLM+OtWSfB4sepCfH0AoodBuBO27i+CD2szasKKALVVayelGfu64nC124UkHXX7B4RZMMe73L7i4Zqh12qigxu/khEMFuMauprwfzTcZR/IjjhkuBa0KQAVRgZkkgdzstwwnMmjTUA5Yacv/78UtWUeiM91zg3Ec24iNjmTtMZpD6flbw/xes4S84jQl7Jc1SzM2F7t3T5/zWau2q5/kZ4cW1WNCdF1BO9ANSGs3aiKJF3AAjTPcKZSE9LN8PGhfO9Bmwhpjcm7gvLN8ERqNKvilJj7adngnsYMkUPWwXLFLPuDYbx2fXWFXDJOTzmREZBOtPVcm/Gk4iEMs53wShnOE/Pc=
  bucket: esoma-sekh
  acl: public_read
  skip_cleanup: true
  local_dir: dist/koality-harmonia-portal