import { NgModule } from '@angular/core';

import {
  MatButtonModule,
  MatToolbarModule,
  MatCheckboxModule,
  MatMenuModule,
  MatIconModule,
  MatCardModule,
  MatInputModule,
  MatSidenavModule,
  MatDividerModule,
  MatListModule,
  MatFormFieldModule,
  MatSelectModule,
  MatTabsModule,
  MatGridListModule,
  MatButtonToggleModule,
  MatSlideToggleModule,
  MatRadioModule,
  MatTableModule,
  MatPaginatorModule,
  MatProgressSpinnerModule,
  MatSnackBarModule,
  MatExpansionModule,
  MatDialogModule,
  MatButtonToggleGroup,
  MatButtonToggle,
  MatSlideToggle,
  MatButton,
  MatRadioGroup,
  MatRadioButton,
  MatTab,
  MatGridList,
  MatGridTile,
  MatPaginator,
  MatSpinner,
  MatAccordion,
  MatExpansionPanel,
  MatExpansionPanelHeader,
  MatExpansionPanelActionRow,
  MatExpansionPanelTitle,
  MatExpansionPanelDescription
} from '@angular/material';

import { MaterialFileInputModule } from 'ngx-material-file-input';

@NgModule({
  declarations: [],
  imports: [
    MatButtonModule,
    MatToolbarModule,
    MatCheckboxModule,
    MatMenuModule,
    MatIconModule,
    MatCardModule,
    MatInputModule,
    MatSidenavModule,
    MatDividerModule,
    MatListModule,
    MatFormFieldModule,
    MatSelectModule,
    MatTabsModule,
    MatGridListModule,
    MatButtonToggleModule,
    MatSlideToggleModule,
    MatRadioModule,
    MatGridListModule,
    MatTableModule,
    MatPaginatorModule,
    MatProgressSpinnerModule,
    MatSnackBarModule,
    MatExpansionModule,
    MatDialogModule,
    MatDividerModule,
    MaterialFileInputModule
  ],
  exports: [
    MatButtonModule,
    MatToolbarModule,
    MatCheckboxModule,
    MatMenuModule,
    MatIconModule,
    MatCardModule,
    MatInputModule,
    MatSidenavModule,
    MatDividerModule,
    MatListModule,
    MatFormFieldModule,
    MatSelectModule,
    MatTabsModule,
    MatGridListModule,
    MatTableModule,
    MatSnackBarModule,
    MatDialogModule,
    MatDividerModule,
    MaterialFileInputModule,
    MatButtonToggleGroup,
    MatButtonToggle,
    MatSlideToggle,
    MatButton,
    MatRadioGroup,
    MatRadioButton,
    MatTab,
    MatGridList,
    MatGridTile,
    MatPaginator,
    MatSpinner,
    MatAccordion,
    MatExpansionPanel,
    MatExpansionPanelHeader,
    MatExpansionPanelActionRow,
    MatExpansionPanelTitle,
    MatExpansionPanelDescription
  ]
})
export class MaterialModule { }
